---
title: "DSCI445 - Term Presentation"
authors: "Jason Nero"
date: "Due 12/05/2022 by 6:10pm"
output: pdf_document
---

```{r, message=FALSE, warning=FALSE}
set.seed(445)  #temp will remove with final work 
#libraries
library(dplyr)
library(tidymodels)
library(tidyverse)
```

```{r}
#setup work
data <- read.csv("HockeyData.csv")
df <- data.frame(data)
data.c <- df %>% filter(Year > 2016)
```

```{R}
#initial inspection
#plot predictors against response 
plot(data.c$Year, data.c$TotalFights, xlab = "Year", ylab = "Total Fights")
plot(data.c$Attendence, data.c$TotalFights)
plot(data.c$Win, data.c$TotalFights)
plot(data.c$Lose, data.c$TotalFights)
plot(data.c$Rank, data.c$TotalFights)
plot(data.c$Points, data.c$TotalFights)
plot(data.c$Goalsfor, data.c$TotalFights)
plot(data.c$Goalsagainst, data.c$TotalFights)

#ggplot this section with year as color (minus first one).  
```

 
Year/TotalFights:
Attendence/TotalFights:
Win/TotalFights:
Lose/TotalFights:
Rank/TotalFights:
Goalsfor/TotalFights:
Goalsagainst/TotalFights:


```{r}
#split dataset

```


```{r}
#determine significant variables
#include cv


```

```{r}
#determine significant model
#include cv


```
