---
title: "DSCI445 - Term Presentation"
authors: "Chien Lin, Jason Nero, Sarah Sublett"
date: "Due 12/15/2022 by 6:10pm"
output: powerpoint_presentation

---
<div class="centered">

Ever Go to a Boxing Match and a Hockey Game Breaks Out? 
Or an Exploration into the Incidence of Fights in Professional Hockey Games.

  Chien Lin

  Jason Nero

  Sarah Sublett

DSCI 445
5 December 2022

</div>

---
### Motivation

-General interest in impact that fines imposed by the NHL in an effort to curb fighting during professional hockey games. 
-Fighting at the professional level encourages similar behavior in junior leagues and fighting, can lead to serious injuries.

---
#### Source of Data

- Utilizing fight data from hockeyfights.com
- Refined fight data for 2017-2021

---
### Challenges with Data

- Several teams were created during the time frame, creating incomplete information
- Utilized omit.na code to compensate

---
### Application of DSCI 445 concepts

- Utilized ggplot, lm, splitting dataset to train and test

---
### Findings

-It could appear that none of variables are statically significant with the exception of the fights subcatgories, which makes sense Totalfights is based off them, and surprisingly Montreal Canadians. 

-Year/TotalFights: Interesting to see that in 2020 there was no physical attendance due to COVID restrictions fights still occurred and in somewhat in line with other years.

---
####### Plots of interest


---
######## Future work


---
######### References


---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

